### ISSUE TITLE
Personal feedback

### ISSUE THREAD

**Issue by CYNAR2k** [jaywcjlove/idoc#69]
Hello.
First of all thanks for your work on this project.
I'm not very skilled with code at all and I followed this guide step by step and somehow I managed to get it working after some good hours...
I think there are some basic and maybe common sense steps missing here like for example telling that you have to need git command line software to make this work...
You also didn't mention that you need to add "deploy": "gh-pages -d dist" on the package.json script to make the command "npm run deploy" work... This command also doesn't work if you don't have git installed.
For some people this might be common sense, but for me it isn't... I had to take some hours to understand why this wasn't working at all.

Also, i had to use google translator in order to follow the rest of the steps since you only gave English instructions for the 1st page.

I would love if you would write a more noob/friendly user guide... Who knows even a youtube video tutorial explaining everything :)

I really like this project that converts markdown files into html websites. 

Thank you!

**Comment by jaywcjlove** [comment]
https://wangchujiang.com/idoc/introduce/index.html

@CYNAR2k There are usage documents, but he is in Chinese.

**Comment by CYNAR2k** [comment]
@jaywcjlove i know the guide is there & in chinese but still i think the guide it's not that friendly user... 
For example i did a website using this, but i'm a little bit confused if i did it right or not.

https://github.com/CYNAR2k/link-z

Like, i only have gh-pages branch. Should the script also create some main branch where there is a README.md file? Or i have to do that manually?

**Comment by jaywcjlove** [comment]
You can place your source code on the main branch and use GitHub actions to compile and deploy it to the gh-pages branch."

[`.github/workflows/main.yml`](https://github.com/jaywcjlove/typenexus/blob/fb1bda81aefd6a33105751c0ab1c09a6a2ff1e2d/.github/workflows/main.yml#L1-L29)

```yml

```bash
name: npm
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - run: npm install
      - run: npm run doc
      - run: tree -I 'node_modules|.git|.github|src' -L 3 -a

      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
```


You can also manage a separate branch and commit the compiled static resources in the 'dist' folder to Git. In the Page settings, select the `dist` folder under the corresponding branch as the directory for static resources.

@CYNAR2k
